import { Capacitor } from '@capacitor/core'

export type GeneratedNativeFile = {
  fileName: string
  blob: Blob
}

type PreparedAndroidFile = {
  fileName: string
  cacheUri: string
  cachePath: string
  persistentSaved: boolean
}

function safeFileName(value: string) {
  return (
    String(value || '')
      .trim()
      .replace(/[\\/:*?"<>|]+/g, '-')
      .replace(/\s+/g, ' ')
      .slice(0, 180) || 'PMS10-Aide-Memoire'
  )
}

function blobToBase64(blob: Blob) {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader()

    reader.onerror = () => {
      reject(
        reader.error ||
          new Error('Unable to prepare the generated file for Android.'),
      )
    }

    reader.onload = () => {
      const result = String(reader.result || '')
      const commaIndex = result.indexOf(',')

      if (commaIndex < 0) {
        reject(
          new Error('Unable to encode the generated file for Android.'),
        )
        return
      }

      resolve(result.slice(commaIndex + 1))
    }

    reader.readAsDataURL(blob)
  })
}

function isUserCancellation(error: unknown) {
  const message =
    error instanceof Error ? error.message : String(error || '')

  return /cancel|canceled|cancelled|dismiss/i.test(message)
}

function absolutePathFromFileUri(uri: string) {
  if (!uri.startsWith('file://')) return uri

  try {
    return decodeURIComponent(uri.replace(/^file:\/\//, ''))
  } catch {
    return uri.replace(/^file:\/\//, '')
  }
}

function preferPdf(files: PreparedAndroidFile[]) {
  return (
    files.find((file) => /\.pdf$/i.test(file.fileName)) ||
    files[0]
  )
}

async function prepareAndroidFile(
  file: GeneratedNativeFile,
  folderStamp: string,
): Promise<PreparedAndroidFile> {
  const { Directory, Filesystem } = await import('@capacitor/filesystem')

  const fileName = safeFileName(file.fileName)
  const data = await blobToBase64(file.blob)

  // Always create a cache copy. Capacitor Share allows cache files by default,
  // and File Viewer can open this exact native file.
  const cachePath = `pms10/aide-memoire/${folderStamp}/${fileName}`
  const cacheWrite = await Filesystem.writeFile({
    path: cachePath,
    data,
    directory: Directory.Cache,
    recursive: true,
  })

  const stat = await Filesystem.stat({
    path: cachePath,
    directory: Directory.Cache,
  })

  if (!Number.isFinite(Number(stat.size)) || Number(stat.size) <= 0) {
    throw new Error(
      `PMS10 created an empty ${fileName} file. Please generate it again.`,
    )
  }

  // Also create a persistent copy in the device Documents directory.
  // This is best-effort: if Android blocks Documents access on an older device,
  // the verified cache copy remains available for Preview/Share.
  let persistentSaved = false

  try {
    await Filesystem.writeFile({
      path: `PMS10/Aide Memoire/${fileName}`,
      data,
      directory: Directory.Documents,
      recursive: true,
    })
    persistentSaved = true
  } catch (error) {
    console.warn(
      '[PMS10 Android] Could not persist Aide Memoire to Documents; cache preview/share remains available.',
      error,
    )
  }

  return {
    fileName,
    cacheUri: cacheWrite.uri,
    cachePath,
    persistentSaved,
  }
}

async function openWithNativeViewer(file: PreparedAndroidFile) {
  const { FileViewer } = await import('@capacitor/file-viewer')

  await FileViewer.openDocumentFromLocalPath({
    path: absolutePathFromFileUri(file.cacheUri),
  })
}

async function shareOneFile(file: PreparedAndroidFile) {
  const { Share } = await import('@capacitor/share')

  await Share.share({
    title: 'PMS10 Aide Memoire',
    text: 'Aide Memoire generated by PMS10.',
    // For one local file, Capacitor explicitly supports the url field and it
    // is more broadly handled by Android receiving apps than a one-item files[].
    url: file.cacheUri,
    dialogTitle: 'Open, save, or share Aide Memoire',
  })
}

async function shareMultipleFiles(files: PreparedAndroidFile[]) {
  const { Share } = await import('@capacitor/share')

  await Share.share({
    title: 'PMS10 Aide Memoire',
    text: 'Aide Memoire files generated by PMS10.',
    files: files.map((file) => file.cacheUri),
    dialogTitle: 'Open, save, or share Aide Memoire files',
  })
}

export async function deliverGeneratedFilesOnAndroid(
  files: GeneratedNativeFile[],
): Promise<boolean> {
  if (
    !Capacitor.isNativePlatform() ||
    Capacitor.getPlatform() !== 'android' ||
    files.length === 0
  ) {
    return false
  }

  const folderStamp = new Date()
    .toISOString()
    .replace(/[:.]/g, '-')

  const prepared: PreparedAndroidFile[] = []

  for (const file of files) {
    prepared.push(await prepareAndroidFile(file, folderStamp))
  }

  const persistentCount = prepared.filter(
    (file) => file.persistentSaved,
  ).length

  if (persistentCount > 0) {
    console.info(
      `[PMS10 Android] Saved ${persistentCount} Aide Memoire file(s) to Documents/PMS10/Aide Memoire.`,
    )
  }

  // For a single PDF/DOCX, open the generated file immediately so the user
  // actually sees the output. If there is no compatible viewer installed,
  // fall back to Android's share/open sheet.
  if (prepared.length === 1) {
    try {
      await openWithNativeViewer(prepared[0])
      return true
    } catch (viewerError) {
      console.warn(
        '[PMS10 Android] Native file viewer could not open the generated file; falling back to Share.',
        viewerError,
      )

      try {
        await shareOneFile(prepared[0])
      } catch (shareError) {
        if (!isUserCancellation(shareError)) throw shareError
      }

      return true
    }
  }

  // "Both" mode: both files are already persisted in Documents. Prefer to
  // share both together. If an Android receiving app rejects multi-file share,
  // at least open the PDF (or first file) so the generated output is visible.
  try {
    await shareMultipleFiles(prepared)
    return true
  } catch (shareError) {
    if (isUserCancellation(shareError)) return true

    console.warn(
      '[PMS10 Android] Multi-file share failed; opening the generated file instead.',
      shareError,
    )

    try {
      await openWithNativeViewer(preferPdf(prepared))
      return true
    } catch (viewerError) {
      console.error(
        '[PMS10 Android] Unable to open or share generated Aide Memoire.',
        viewerError,
      )
      throw shareError
    }
  }
}

export async function openGeneratedFileOnAndroid(
  file: GeneratedNativeFile,
): Promise<boolean> {
  if (
    !Capacitor.isNativePlatform() ||
    Capacitor.getPlatform() !== 'android'
  ) {
    return false
  }

  const folderStamp = new Date()
    .toISOString()
    .replace(/[:.]/g, '-')

  const prepared = await prepareAndroidFile(file, folderStamp)
  await openWithNativeViewer(prepared)
  return true
}

export async function shareGeneratedFilesOnAndroid(
  files: GeneratedNativeFile[],
): Promise<boolean> {
  if (
    !Capacitor.isNativePlatform() ||
    Capacitor.getPlatform() !== 'android' ||
    files.length === 0
  ) {
    return false
  }

  const folderStamp = new Date()
    .toISOString()
    .replace(/[:.]/g, '-')

  const prepared: PreparedAndroidFile[] = []

  for (const file of files) {
    prepared.push(await prepareAndroidFile(file, folderStamp))
  }

  if (prepared.length === 1) {
    await shareOneFile(prepared[0])
    return true
  }

  await shareMultipleFiles(prepared)
  return true
}
